baseURL = 'https://zesty-snickerdoodle-c1887f.netlify.app/'
languageCode = 'ca'
locale = 'ca'
title = 'Nau Bostik'
theme = "thema"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Un espai cultural autogestionat a Barcelona"

[[menu.main]]
  name = "Inici"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Activitats"
  url = "/activitats/"
  weight = 2

[[menu.main]]
  name = "Notícies"
  url = "/noticies/"
  weight = 3

[[menu.main]]
  name = "Col·lectius"
  url = "/collectius/"
  weight = 4

[[menu.main]]
  name = "Espais"
  url = "/espais/"
  weight = 5

[[menu.main]]
  name = "Contacte"
  url = "/contacte/"
  weight = 6
