backend:
  name: git-gateway
  branch: main

local_backend: true

# Enable Netlify Identity widget
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://zesty-snickerdoodle-c1887f.netlify.app
display_url: https://zesty-snickerdoodle-c1887f.netlify.app

collections:
  - name: "noticies"
    label: "Notícies"
    folder: "content/noticies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Cos", name: "body", widget: "markdown"}

  - name: "espais"
    label: "Espais"
    folder: "content/espais"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Cos", name: "body", widget: "markdown"}

  - name: "activitats"
    label: "Activitats"
    folder: "content/activitats"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Cos", name: "body", widget: "markdown"}

  - name: "collectius"
    label: "Col·lectius"
    folder: "content/collectius"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Cos", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pàgines"
    files:
      - label: "Inici"
        name: "inici"
        file: "content/_index.md"
        fields:
          - {label: "Títol", name: "title", widget: "string"}
          - {label: "Cos", name: "body", widget: "markdown"}
